version: 2
root-markers:
  - .git/

provide-definition: true

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  prettier: &prettier
    format-command: './node_modules/.bin/prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}'

  golint: &golint
    lint-command: 'golint'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'

  goimports: &goimports
    format-command: 'goimports'
    format-stdin: true

  black: &black
    format-command: 'black -'
    format-stdin: true

  isort: &isort
    format-command: 'isort --stdout -'
    format-stdin: true

  flake8: &flake8
    lint-command: 'flake8 --max-line-length 160 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  mypy: &mypy
    lint-command: 'mypy --show-column-numbers --ignore-missing-imports'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  terraform: &terraform
    format-command: 'terraform fmt -'
    format-stdin: true

  luafmt: &luafmt
    format-command: 'luafmt --stdin'
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  vim:
    - <<: *vim-vint
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
  go:
    - <<: *goimports
    - <<: *golint
  python:
    - <<: *black
    - <<: *isort
    - <<: *flake8
    - <<: *mypy
  tf:
    - <<: *terraform
  lua:
    - <<: *luafmt
  sh:
    - <<: *shellcheck
